#ifndef INCLUDE_INCLUDE_RAVEN_H_
#define INCLUDE_INCLUDE_RAVEN_H_

#define RAVEN_MAJOR "0"
#define RAVEN_MINOR "0"
#define RAVEN_PATCH "0"
#define RAVEN_VERSION "v" RAVEN_MAJOR "." RAVEN_MINOR "." RAVEN_PATCH

#endif // INCLUDE_INCLUDE_RAVEN_H_
